FROM node:12.3.1-stretch as builder

RUN npm i -g @vue/cli

RUN mkdir -p /app
WORKDIR /app

ADD app /app

RUN npm i

RUN npm run build

FROM nginx:1.13

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
