version: '3'
services:
  flash_spanish:
    build: .
    ports:
      - 28080:8080
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
  bash:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secret/service-account.json
    volumes:
      - ./app:/app
      - ./secret:/secret
